load("@rules_python//python:defs.bzl", "py_library")
package(default_visibility = ["//visibility:public"])

py_library(
    name = "beam",
    srcs = [
        "__init__.py",
        "arrayrecordio.py",
        "demo.py",
        "dofns.py",
        "example.py",
        "options.py",
        "pipelines.py",
        "testdata.py",
    ]
)