package(
    default_applicable_licenses = ["//third_party/array_record:license"],
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

exports_files(glob(["*.array_record-*"]))
