# This workflow builds ArrayRecord wheels and uploads them as artifacts.

name: Build & Publish Template

on:
  workflow_call:
    inputs:
      pypi_project_url:
        required: false
        type: string
      upload_wheels:
        required: true
        type: boolean

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build-and-test:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-14]

    env:
      USE_BAZEL_VERSION: "7.2.1"
    steps:
      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@4fd964a13a440a8aeb0be47350db2fc640f19ca8 # 0.15.0
      - name: Check Bazel installation
        run: |
          which bazel
          bazel version
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Create directory
        run: |
          mkdir -p /tmp/array_record
          cp -r . /tmp/array_record
      - name: Build package
        run: |
          set -xe
          export PYTHON_VERSION=${{ matrix.python-version }}
          export PYTHON_MAJOR_VERSION=$(echo $PYTHON_VERSION | cut -d. -f1)
          export PYTHON_MINOR_VERSION=$(echo $PYTHON_VERSION | cut -d. -f2)
          export BAZEL_VERSION="7.2.1"
          export OUTPUT_DIR="/tmp/array_record"
          export SOURCE_DIR="/tmp/array_record"
          . "${SOURCE_DIR}"'/oss/runner_common.sh'
          build_and_test_array_record
      - name: Upload ArrayRecord artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: built-array-record-wheels-${{ matrix.os }}-${{ matrix.python-version }}
          path: /tmp/array_record/all_dist/*.whl

  publish-wheel:
    if: ${{ inputs.upload_wheels }}
    runs-on: ubuntu-22.04
    needs: build-and-test
    permissions:
      id-token: write
    environment:
      name: pypi
      url: ${{ inputs.pypi_project_url }}
    steps:
      - name: Download ArrayRecord artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          pattern: built-array-record-wheels-*
          path: dist/
          merge-multiple: true
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # release/v1
        with:
          attestations: false
          verbose: true