name: Build and Publish Release

on: workflow_dispatch

jobs:
  call-workflow:
    uses: ./.github/workflows/build_and_publish_template.yml
    permissions:
      contents: read
      id-token: write
    with:
      pypi_project_url: https://pypi.org/project/array-record
      upload_wheels: true
